<div>
    <ul class="video_gallery">
        <li class="list_videos relative slide-left" ng-repeat="video in collection">
            <div sb-video video="video"></div>
        </li>
    </ul>

    <sb-loader is-loading="show_loader_more" size="'48'" block="'background'"></sb-loader>

    <div class="padding" ng-if="!show_loader_more && enable_load_onscroll">
        <button type="button" class="button" ng-click="loadMore();"><?php echo $this->_("Load More"); ?></button>
    </div>
</div>