<?php $option_value = $this->getOptionValue(); ?>
<?php $application = $this->getApplication(); ?>
<?php $features = $application->getOptions(); ?>
<?php $padlock = new Padlock_Model_Padlock(); ?>
<?php $padlock->find($option_value->getId(), 'value_id') ?>
<div class="form_content">
    <div id="list" class="edit_page padlock">
        <div class="section form_content">
            <form id="padlockForm" name="padlockForm" method="post" action="<?php echo $this->getUrl('padlock/application/editpost') ?>">
                <h4 class="subtitle">
                    <span class="left area"><?php echo $this->_('Restrict Access') ?></span>
                    <hr class="area reverse">
                    <div class="clear"></div>
                </h4>
                <input type="hidden" name="value_id" value="<?php echo $option_value->getId(); ?>" />
                <div class="form_content">
                    <div class="infos">
                        <div id="padlock_content">

                            <table class="no-collapse" cellspacing="10">
                                <tr>
                                    <td class="label"><label for="allow_all_customers_to_access_locked_features"><?php echo $this->_("Allow all the users by default:") ?></label></td>
                                    <td>
                                        <select id="allow_all_customers_to_access_locked_features" name="allow_all_customers_to_access_locked_features">
                                            <option value="1"<?php if($application->getAllowAllCustomersToAccessLockedFeatures()) : ?> selected="selected"<?php endif; ?>><?php echo $this->_("Yes"); ?></option>
                                            <option value="0"<?php if(!$application->getAllowAllCustomersToAccessLockedFeatures()) : ?> selected="selected"<?php endif; ?>><?php echo $this->_("No"); ?></option>
                                        </select>
                                    </td>
                                </tr>
                            </table>

                            <table class="no-collapse" cellspacing="10">
                                <tr>
                                    <td class="label"><label for="lock_the_entire_app"><?php echo $this->_("Lock the entire application?") ?></label></td>
                                    <td>
                                        <select id="lock_the_entire_app" name="app_is_locked">
                                            <option value="1"<?php if($application->requireToBeLoggedIn()) : ?> selected="selected"<?php endif; ?>><?php echo $this->_("Yes"); ?></option>
                                            <option value="0"<?php if(!$application->requireToBeLoggedIn()) : ?> selected="selected"<?php endif; ?>><?php echo $this->_("No"); ?></option>
                                        </select>
                                    </td>
                                </tr>
                            </table>

                            <div id="select_features_to_lock"<?php if($application->requireToBeLoggedIn()) : ?> style="display:none"<?php endif; ?>>
                                <hr class="separator" />
                                <div><p><?php echo $this->_('Choose the features to lock:'); ?></p></div>
                                <ul class="clear tree">
                                    <?php foreach($features as $feature) : ?>
                                        <?php if($feature->getCode() == 'padlock' OR !$feature->getIsVisible()) continue; ?>
                                        <li class="level_1">
                                            <label for="select_option_value_<?php echo $feature->getId(); ?>" id="label_select_option_value_<?php echo $feature->getId(); ?>" class="label_select_option_value checkbox left">
                                                <input type="checkbox" class="select_option_value" value="<?php echo $feature->getId(); ?>" name="value_ids[]" id="select_option_value_<?php echo $feature->getId(); ?>"<?php if($feature->isLocked()) : ?> checked="checked"<?php endif; ?>>
                                                <?php echo $feature->getTabbarName() ?>
                                            </label>
                                            <div class="clear"></div>
                                        </li>
                                    <?php endforeach ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="save right">
                        <button class="default_button btn-block" type="submit">
                            <?php echo $this->_('Save'); ?>
                        </button>
                    </div>
                    <div class="clear"></div>
                </div>
            </form>
        </div>
        <div class="section">
            <?php
                echo $this->getLayout()
                    ->addPartial('background_image', 'Core_View_Default', 'application/customization/features/edit/background_image.phtml')
                    ->setValueId($option_value->getId())
                    ->toHtml()
                ;
            ?>
        </div>
    </div>
    <style>
        .edit_page.padlock .dk_container.dk_shown {margin-bottom: 0;}
    </style>
    <script type="text/javascript">

        page.setCallback('didappear', function() {

            createCustomUI();
            $('#lock_the_entire_app').dropkick({
                change: function() {
                    if(this.val() == 1) {
                        $('#select_features_to_lock').stop().slideUp();
                    } else {
                        $('#select_features_to_lock').stop().slideDown();
                    }
                }
            });
            $('#allow_all_customers_to_access_locked_features').dropkick({});

            $('#padlockForm').submit(function() {
                reload(this, this.action, true, function(datas) {

                });
                return false;
            });

        });

        page.setCallback('willdisappear', function() {
            $('#padlock').unbind('change');
            $('#padlockForm').unbind('submit');
        });

    </script>
</div>
