<?php
$dolibarr_main_url_root='http://ipx-lab.com/gestion/htdocs';
$dolibarr_main_document_root='/homez.717/ipxlabcoag/www/gestion/htdocs';
$dolibarr_main_data_root='/homez.717/ipxlabcoag/www/gestion/documents';
$dolibarr_main_db_host='sql24.modules';
$dolibarr_main_db_port='';
$dolibarr_main_db_name='4621867-2';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='4621867-2';
$dolibarr_main_db_pass='myYXhJzC';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
$dolibarr_main_authentication='dolibarr';
$dolibarr_main_prod='0';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_force_https='0';
$dolibarr_main_cookie_cryptkey='zYI0c5Tyi8tU70WTCtXdmQ';
$dolibarr_mailing_limit_sendbyweb='0';
?>
